/**
 * 必殺技：虹
 * 参照ファイル：特能 (9).xlsx - 虹必殺技.csv
 */
const HISSATSU_SKILLS = [
  {"name": "スラッシュ", "category": "必殺技・虹", "costs": {"muscle": 155, "agile": 44, "tech": 67, "intel": 0, "mental": 0}, "effect": "敵前衛1体に威力90の物理ダメージ。", "condition": "剣士"},
  {"name": "パワーシュート", "category": "必殺技・虹", "costs": {"muscle": 60, "agile": 80, "tech": 110, "intel": 0, "mental": 0}, "effect": "物理防御力が最も低い敵中衛1体に威力90の物理ダメージ。", "condition": "弓使い"},
  {"name": "マジックバレット", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 67, "intel": 111, "mental": 89}, "effect": "敵前衛1体に威力90の魔法ダメージ。", "condition": "魔法使い"},
  {"name": "マジックアッパー", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 20, "tech": 80, "intel": 150, "mental": 0}, "effect": "敵前衛1体に威力90の魔法ダメージ。", "condition": "魔闘士"},
  {"name": "守りの態勢", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 177, "tech": 0, "intel": 0, "mental": 89}, "effect": "自身の物理攻撃耐性を13％アップ。さらに魔法攻撃耐性を13％アップ。3ターン継続。", "condition": "重戦士"},
  {"name": "メガヒール", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 89, "mental": 177}, "effect": "HP割合が最も低い味方1人に威力50のHP回復。", "condition": "僧侶"},
  {"name": "ライジングストライクLv.1", "category": "必殺技・虹", "costs": {"muscle": 254, "agile": 50, "tech": 152, "intel": 0, "mental": 100}, "effect": "敵前衛1体に威力120の物理ダメージ。", "condition": "剣士／火属性／パワーE40"},
  {"name": "ライジングストライクLv.2", "category": "必殺技・虹", "costs": {"muscle": 378, "agile": 76, "tech": 226, "intel": 0, "mental": 150}, "effect": "敵前衛1体に威力180の物理ダメージ。", "condition": "剣士／火属性／パワーC60", "prerequisite": "ライジングストライクLv.1"},
  {"name": "テンペストスイープLv.1", "category": "必殺技・虹", "costs": {"muscle": 254, "agile": 50, "tech": 152, "intel": 0, "mental": 100}, "effect": "敵前衛1体に威力120の物理ダメージ。", "condition": "剣士／風属性／パワーE40"},
  {"name": "テンペストスイープLv.2", "category": "必殺技・虹", "costs": {"muscle": 378, "agile": 76, "tech": 226, "intel": 0, "mental": 150}, "effect": "敵前衛1体に威力180の物理ダメージ。", "condition": "剣士／風属性／パワーC60", "prerequisite": "テンペストスイープLv.1"},
  {"name": "渦巻く剣刃Lv.1", "category": "必殺技・虹", "costs": {"muscle": 126, "agile": 50, "tech": 210, "intel": 0, "mental": 168}, "effect": "自身に反撃状態を付与する。4ターン継続。反撃発生時に攻撃してきた相手に対して威力50の物理ダメージ。", "condition": "剣士／水属性／パワーF20／耐久力F20"},
  {"name": "渦巻く剣刃Lv.2", "category": "必殺技・虹", "costs": {"muscle": 188, "agile": 76, "tech": 314, "intel": 0, "mental": 252}, "effect": "自身に反撃状態を付与する。4ターン継続。反撃発生時に攻撃してきた相手に対して威力75の物理ダメージ。", "condition": "剣士／水属性／パワーD50／耐久力D50", "prerequisite": "渦巻く剣刃Lv.1"},
  {"name": "レインバーンLv.1", "category": "必殺技・虹", "costs": {"muscle": 152, "agile": 146, "tech": 164, "intel": 110, "mental": 0}, "effect": "敵中衛全体に威力42の物理ダメージ。さらに物理攻撃力7％分の火傷状態を付与する。3ターン継続。", "condition": "弓使い／火属性／パワーF20／器用さF20"},
  {"name": "レインバーンLv.2", "category": "必殺技・虹", "costs": {"muscle": 226, "agile": 188, "tech": 252, "intel": 164, "mental": 0}, "effect": "敵中衛全体に威力63の物理ダメージ。さらに物理攻撃力11％分の火傷状態を付与する。3ターン継続。", "condition": "弓使い／火属性／パワーE40／器用さD50", "prerequisite": "レインバーンLv.1"},
  {"name": "ゲイルシュートLv.1", "category": "必殺技・虹", "costs": {"muscle": 194, "agile": 100, "tech": 210, "intel": 50, "mental": 0}, "effect": "敵前衛1体に威力120の物理ダメージ。", "condition": "弓使い／風属性／パワーF20／器用さF20"},
  {"name": "ゲイルシュートLv.2", "category": "必殺技・虹", "costs": {"muscle": 290, "agile": 150, "tech": 314, "intel": 76, "mental": 0}, "effect": "敵前衛1体に威力180の物理ダメージ。", "condition": "弓使い／風属性／パワーE40／器用さD50", "prerequisite": "ゲイルシュートLv.1"},
  {"name": "夢幻の水矢Lv.1", "category": "必殺技・虹", "costs": {"muscle": 110, "agile": 186, "tech": 210, "intel": 50, "mental": 0}, "effect": "敵後衛全体に威力43の物理ダメージ。さらに睡眠状態を付与する。1ターン継続。", "condition": "弓使い／水属性／器用さE40"},
  {"name": "夢幻の水矢Lv.2", "category": "必殺技・虹", "costs": {"muscle": 164, "agile": 276, "tech": 314, "intel": 76, "mental": 0}, "effect": "敵後衛全体に威力63の物理ダメージ。さらに睡眠状態を付与する。1ターン継続。", "condition": "弓使い／水属性／器用さC60", "prerequisite": "夢幻の水矢Lv.1"},
  {"name": "エクスプロ―ジョンLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 54, "tech": 104, "intel": 254, "mental": 134}, "effect": "敵後衛全体に威力42の魔法ダメージ。さらに魔法攻撃力7％分の火傷状態を付与する。3ターン継続。", "condition": "魔法使い／火属性／魔力E40"},
  {"name": "エクスプロ―ジョンLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 82, "tech": 170, "intel": 378, "mental": 200}, "effect": "敵後衛全体に威力63の魔法ダメージ。さらに魔法攻撃力11％分の火傷状態を付与する。3ターン継続。", "condition": "魔法使い／火属性／魔力C60", "prerequisite": "エクスプロ―ジョンLv.1"},
  {"name": "トキシックブリーズLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "魔法使い／風属性／魔力E40"},
  {"name": "トキシックブリーズLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "魔法使い／風属性／魔力C60", "prerequisite": "トキシックブリーズLv.1"},
  {"name": "マリンスフィアLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 50, "tech": 96, "intel": 274, "mental": 134}, "effect": "敵前衛1体に威力84の魔法ダメージ。さらに敵前衛全体に威力18の魔法ダメージ。", "condition": "魔法使い／水属性／魔力E40"},
  {"name": "マリンスフィアLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 76, "tech": 144, "intel": 408, "mental": 200}, "effect": "敵前衛1体に威力126の魔法ダメージ。さらに敵前衛全体に威力27の魔法ダメージ。", "condition": "魔法使い／水属性／魔力C60", "prerequisite": "マリンスフィアLv.1"},
  {"name": "爆熱フィストLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 172, "tech": 110, "intel": 224, "mental": 50}, "effect": "敵前衛1体に威力84の魔法ダメージ。この攻撃は対象にかかっている火傷状態の数の応じて必殺技倍率が12％アップ。", "condition": "魔闘士／火属性／魔力E40"},
  {"name": "爆熱フィストLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 258, "tech": 164, "intel": 334, "mental": 76}, "effect": "敵前衛1体に威力126の魔法ダメージ。この攻撃は対象にかかっている火傷状態の数の応じて必殺技倍率が18％アップ。", "condition": "魔闘士／火属性／魔力C60", "prerequisite": "爆熱フィストLv.1"},
  {"name": "インサイトブローLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 172, "tech": 110, "intel": 224, "mental": 50}, "effect": "敵前衛1体に威力17の魔法ダメージを5回与える。自身に追撃◎状態を付与する。2ターン継続。", "condition": "魔闘士／風属性／魔力E40"},
  {"name": "インサイトブローLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 258, "tech": 164, "intel": 334, "mental": 76}, "effect": "敵前衛1体に威力25の魔法ダメージを5回与える。自身に追撃◎状態を付与する.2ターン継続。", "condition": "魔闘士／風属性／魔力C60", "prerequisite": "インサイトブローLv.1"},
  {"name": "水脚乱舞Lv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 172, "tech": 130, "intel": 202, "mental": 50}, "effect": "敵前衛1体に威力28の魔法ダメージを3回与える。自身に反撃◎状態を付与する。4ターン継続。反撃◎発生時に攻撃してきた相手に対して威力20の魔法ダメージ。", "condition": "魔闘士／水属性／魔力F20／器用さF20"},
  {"name": "水脚乱舞Lv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 258, "tech": 194, "intel": 302, "mental": 78}, "effect": "敵前衛1体に威力42の魔法ダメージを3回与える。自身に反撃◎状態を付与する。4ターン継続。反撃◎発生時に攻撃してきた相手に対して威力30の魔法ダメージ。", "condition": "魔闘士／水属性／魔力D50／器用さE40", "prerequisite": "水脚乱舞Lv.1"},
  {"name": "ルミナスオーラLv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "重戦士／火属性／"},
  {"name": "ルミナスオーラLv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "重戦士／火属性／", "prerequisite": "ルミナスオーラLv.1"},
  {"name": "守りの鼓舞Lv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 254, "tech": 50, "intel": 0, "mental": 254}, "effect": "自身と同じポジションにいる味方全員の物理攻撃耐性を9％アップ。さらに魔法攻撃耐性を9％アップ。4ターン継続。", "condition": "重戦士／水属性／耐久力E40"},
  {"name": "守りの鼓舞Lv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 376, "tech": 76, "intel": 0, "mental": 378}, "effect": "自身と同じポジションにいる味方全員の物理攻撃耐性を14％アップ。さらに魔法攻撃耐性を14％アップ。4ターン継続。", "condition": "重戦士／水属性／耐久力C60", "prerequisite": "守りの鼓舞Lv.1"},
  {"name": "爽風の破動Lv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 114, "tech": 54, "intel": 254, "mental": 134}, "effect": "自身と同じポジションにいる味方全員に威力30のHP回復。敵前衛全体の反撃状態を解除する。", "condition": "僧侶／風属性／魔力E40"},
  {"name": "爽風の破動Lv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 190, "tech": 82, "intel": 378, "mental": 200}, "effect": "自身と同じポジションにいる味方全員に威力44のHP回復。敵前衛全体の反撃状態を解除する。", "condition": "僧侶／風属性／魔力C60", "prerequisite": "爽風の破動Lv.1"},
  {"name": "生命の雫Lv.1", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "僧侶／水属性／"},
  {"name": "生命の雫Lv.2", "category": "必殺技・虹", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "効果データなし", "condition": "僧侶／水属性／", "prerequisite": "生命の雫Lv.1"}
];