/**
 * プリスキンのパワアド育成ナビ - 特殊能力（サポートスキル）
 * 最終更新: 2026/04/04
 * 「青・金・青赤」すべてのパッシブ特能を網羅（最新リスト反映版）
 */

const SUPPORT_SKILLS = [
    // --- サポートスキル・青 ---
    { name: "物理攻撃○", category: "特殊能力・青", costs: { muscle: 190, agile: 15, tech: 65, intel: 0, mental: 0 }, condition: "なし", effect: "自身の物理攻撃倍率を3%アップ。" },
    { name: "物理攻撃◎", category: "特殊能力・青", costs: { muscle: 285, agile: 22, tech: 98, intel: 0, mental: 0 }, condition: "なし", effect: "自身の物理攻撃倍率を5%アップ。" },
    { name: "魔法攻撃○", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 30, intel: 170, mental: 70 }, condition: "なし", effect: "自身の魔法攻撃倍率を3%アップ。" },
    { name: "魔法攻撃◎", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 45, intel: 255, mental: 105 }, condition: "なし", effect: "自身の魔法攻撃倍率を5%アップ。" },
    { name: "物理防御○", category: "特殊能力・青", costs: { muscle: 90, agile: 150, tech: 0, intel: 0, mental: 35 }, condition: "なし", effect: "自身の物理攻撃耐性を2%アップ。" },
    { name: "物理防御◎", category: "特殊能力・青", costs: { muscle: 135, agile: 225, tech: 0, intel: 0, mental: 45 }, condition: "なし", effect: "自身の物理攻撃耐性を4%アップ。" },
    { name: "魔法防御○", category: "特殊能力・青", costs: { muscle: 0, agile: 150, tech: 0, intel: 70, mental: 55 }, condition: "なし", effect: "自身の魔法攻撃耐性を2%アップ。" },
    { name: "魔法防御◎", category: "特殊能力・青", costs: { muscle: 0, agile: 225, tech: 0, intel: 105, mental: 75 }, condition: "なし", effect: "自身の魔法攻撃耐性を4%アップ。" },
    { name: "体幹", category: "特殊能力・青", costs: { muscle: 230, agile: 0, tech: 0, intel: 0, mental: 60 }, condition: "なし", effect: "自身の物理攻撃倍率を2%アップ。さらに物理攻撃耐性を1%アップ。" },
    { name: "魔力制御", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 0, intel: 230, mental: 60 }, condition: "なし", effect: "自身の魔法攻撃倍率を2%アップ。さらに魔法攻撃耐性を1%アップ。" },
    { name: "忍耐", category: "特殊能力・青", costs: { muscle: 170, agile: 0, tech: 0, intel: 0, mental: 120 }, condition: "なし", effect: "自身のHPを3％アップ。" },
    { name: "生存本能", category: "特殊能力・青", costs: { muscle: 0, agile: 110, tech: 0, intel: 25, mental: 170 }, condition: "なし", effect: "自身のHPを5％アップ。" },
    { name: "闘争本能", category: "特殊能力・青", costs: { muscle: 80, agile: 0, tech: 0, intel: 0, mental: 225 }, condition: "なし", effect: "自身の物理攻撃倍率を3%アップ。さらに魔法攻撃倍率を3%アップ。" },
    { name: "柔軟な体", category: "特殊能力・青", costs: { muscle: 0, agile: 110, tech: 140, intel: 35, mental: 0 }, condition: "なし", effect: "自身の物理攻撃耐性4%アップ。" },
    { name: "頑丈な体", category: "特殊能力・青", costs: { muscle: 175, agile: 0, tech: 0, intel: 0, mental: 110 }, condition: "なし", effect: "自身のHPを5％アップ。" },
    { name: "無心の構え", category: "特殊能力・青", costs: { muscle: 0, agile: 60, tech: 30, intel: 0, mental: 195 }, condition: "なし", effect: "自身の魔法攻撃耐性4%アップ。" },
    { name: "護身の構え", category: "特殊能力・青", costs: { muscle: 0, agile: 110, tech: 105, intel: 0, mental: 70 }, condition: "なし", effect: "自身のHPを5％アップ。" },
    { name: "狙い撃ち", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 195, intel: 0, mental: 95 }, condition: "なし", effect: "自身の命中率を2％アップ。" },
    { name: "火攻撃", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 180, intel: 40, mental: 60 }, condition: "火属性", effect: "自身の火属性倍率3%アップ。" },
    { name: "風攻撃", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 180, intel: 40, mental: 60 }, condition: "風属性", effect: "自身の風属性倍率3%アップ。" },
    { name: "水攻撃", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 180, intel: 40, mental: 60 }, condition: "水属性", effect: "自身の水属性倍率3%アップ。" },
    { name: "火耐性", category: "特殊能力・青", costs: { muscle: 0, agile: 120, tech: 60, intel: 0, mental: 100 }, condition: "なし", effect: "自身の火属性耐性を2％アップ。" },
    { name: "風耐性", category: "特殊能力・青", costs: { muscle: 0, agile: 120, tech: 60, intel: 0, mental: 100 }, condition: "なし", effect: "自身の風属性耐性を2％アップ。" },
    { name: "水耐性", category: "特殊能力・青", costs: { muscle: 0, agile: 120, tech: 60, intel: 0, mental: 100 }, condition: "なし", effect: "自身の水属性耐性を2％アップ。" },
    { name: "無耐性", category: "特殊能力・青", costs: { muscle: 0, agile: 120, tech: 60, intel: 0, mental: 100 }, condition: "なし", effect: "自身の無属性耐性を2％アップ。" },
    { name: "通常攻撃○", category: "特殊能力・青", costs: { muscle: 95, agile: 85, tech: 90, intel: 0, mental: 0 }, condition: "なし", effect: "自身の通常攻撃倍率を12%アップ。" },
    { name: "アクションスキル○", category: "特殊能力・青", costs: { muscle: 0, agile: 90, tech: 170, intel: 0, mental: 0 }, condition: "なし", effect: "自身のアクションスキル倍率を12%アップ。" },
    { name: "単体攻撃○", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 90, intel: 0, mental: 300 }, condition: "なし", effect: "自身の単体攻撃倍率を3%アップ。" },
    { name: "単体攻撃◎", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 60, intel: 0, mental: 200 }, condition: "なし", effect: "自身の単体攻撃倍率を3%アップ。" },
    { name: "列攻撃○", category: "特殊能力・青", costs: { muscle: 0, agile: 160, tech: 50, intel: 50, mental: 0 }, condition: "なし", effect: "自身の列攻撃倍率を3%アップ。" },
    { name: "列攻撃◎", category: "特殊能力・青", costs: { muscle: 0, agile: 240, tech: 75, intel: 75, mental: 0 }, condition: "なし", effect: "自身の列攻撃倍率を3%アップ。" },
    { name: "追撃○", category: "特殊能力・青", costs: { muscle: 130, agile: 130, tech: 0, intel: 0, mental: 0 }, condition: "なし", effect: "自身の追撃倍率を3%アップ。" },
    { name: "追撃◎", category: "特殊能力・青", costs: { muscle: 195, agile: 195, tech: 0, intel: 0, mental: 0 }, condition: "なし", effect: "自身の追撃倍率を5%アップ。" },
    { name: "けがしにくさ○", category: "特殊能力・青", costs: { muscle: 190, agile: 0, tech: 0, intel: 0, mental: 80 }, condition: "なし", effect: "自身の物理攻撃耐性を1％アップ。さらに魔法攻撃耐性を1％アップ。" },
    { name: "けがしにくさ◎", category: "特殊能力・青", costs: { muscle: 285, agile: 0, tech: 0, intel: 0, mental: 120 }, condition: "なし", effect: "自身の物理攻撃耐性を2％アップ。さらに魔法攻撃耐性を2％アップ。" },
    { name: "防御体制", category: "特殊能力・青", costs: { muscle: 155, agile: 135, tech: 0, intel: 0, mental: 0 }, condition: "なし", effect: "自身の単体攻撃耐性を2％アップ。" },
    { name: "備え", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 60, intel: 90, mental: 140 }, condition: "なし", effect: "自身の列攻撃耐性を2％アップ。" },
    { name: "広い視野", category: "特殊能力・青", costs: { muscle: 0, agile: 170, tech: 0, intel: 60, mental: 60 }, condition: "なし", effect: "自身の全体攻撃耐性を2％アップ。" },
    { name: "見切り", category: "特殊能力・青", costs: { muscle: 65, agile: 95, tech: 130, intel: 0, mental: 0 }, condition: "なし", effect: "自身のアクションスキル耐性4%アップ。" },
    { name: "危機察知", category: "特殊能力・青", costs: { muscle: 120, agile: 50, tech: 115, intel: 0, mental: 0 }, condition: "なし", effect: "自身の必殺技耐性を4％アップ。" },
    { name: "力学の理解", category: "特殊能力・青", costs: { muscle: 80, agile: 0, tech: 0, intel: 230, mental: 0 }, condition: "なし", effect: "自身の物理攻撃耐性を4％アップ。" },
    { name: "魔法の理解", category: "特殊能力・青", costs: { muscle: 0, agile: 0, tech: 0, intel: 310, mental: 0 }, condition: "なし", effect: "自身の魔法攻撃耐性を4％アップ。" },
    { name: "免疫強化", category: "特殊能力・青赤", costs: { muscle: 70, agile: 0, tech: 86, intel: 104, mental: 0 }, condition: "なし", effect: "自身のダメージ状態異常耐性を2%アップ。" },
    { name: "意志", category: "特殊能力・青赤", costs: { muscle: 0, agile: 0, tech: 142, intel: 46, mental: 0 }, condition: "なし", effect: "自身の弱体化状態異常耐性を2%アップ。" },
    { name: "ガッツ", category: "特殊能力・青赤", costs: { muscle: 140, agile: 0, tech: 0, intel: 24, mental: 6 }, condition: "なし", effect: "自身の行動不能状態異常耐性を2%アップ。" },
    { name: "対剣士○", category: "特殊能力・青", costs: { muscle: 0, agile: 90, tech: 0, intel: 170, mental: 10 }, condition: "なし", effect: "自身の剣士特効を2％アップ。" },
    { name: "対剣士◎", category: "特殊能力・青", costs: { muscle: 0, agile: 135, tech: 0, intel: 255, mental: 15 }, condition: "なし", effect: "自身の剣士特効を3％アップ。" },
    { name: "対魔闘士○", category: "特殊能力・青", costs: { muscle: 25, agile: 40, tech: 0, intel: 0, mental: 205 }, condition: "なし", effect: "自身の魔闘士特効を2％アップ。" },
    { name: "対魔闘士◎", category: "特殊能力・青", costs: { muscle: 37, agile: 60, tech: 0, intel: 0, mental: 308 }, condition: "なし", effect: "自身の魔闘士特効を3％アップ。" },
    { name: "対弓使い○", category: "特殊能力・青", costs: { muscle: 0, agile: 205, tech: 0, intel: 0, mental: 65 }, condition: "なし", effect: "自身の弓使い特効を2％アップ。" },
    { name: "対弓使い◎", category: "特殊能力・青", costs: { muscle: 0, agile: 308, tech: 0, intel: 0, mental: 97 }, condition: "なし", effect: "自身の弓使い特効を3％アップ。" },
    { name: "対魔法使い○", category: "特殊能力・青", costs: { muscle: 170, agile: 30, tech: 0, intel: 0, mental: 70 }, condition: "なし", effect: "自身の魔法使い特効を2％アップ。" },
    { name: "対魔法使い◎", category: "特殊能力・青", costs: { muscle: 255, agile: 45, tech: 0, intel: 0, mental: 105 }, condition: "なし", effect: "自身の魔法使い特効を3％アップ。" },
    { name: "対ゴブリン○", category: "特殊能力・青", costs: { muscle: 95, agile: 0, tech: 80, intel: 80, mental: 0 }, condition: "なし", effect: "自身のゴブリン特効を2％アップ。" },
    { name: "対ゴブリン◎", category: "特殊能力・青", costs: { muscle: 143, agile: 0, tech: 120, intel: 120, mental: 0 }, condition: "なし", effect: "自身のゴブリン特効を3％アップ。" },
    { name: "対オーク○", category: "特殊能力・青", costs: { muscle: 220, agile: 35, tech: 0, intel: 0, mental: 0 }, condition: "なし", effect: "自身のオーク特効を2％アップ。" },
    { name: "対オーク◎", category: "特殊能力・青", costs: { muscle: 330, agile: 53, tech: 0, intel: 0, mental: 0 }, condition: "なし", effect: "自身のオーク特効を3％アップ。" },
    { name: "対サイクロプス○", category: "特殊能力・青", costs: { muscle: 80, agile: 125, tech: 0, intel: 50, mental: 0 }, condition: "なし", effect: "自身のサイクロプス特効を2％アップ。" },
    { name: "対サイクロプス◎", category: "特殊能力・青", costs: { muscle: 120, agile: 188, tech: 0, intel: 75, mental: 0 }, condition: "なし", effect: "自身のサイクロプス特効を3％アップ。" },
    { name: "対ヌメリン○", category: "特殊能力・青", costs: { muscle: 0, agile: 30, tech: 17, intel: 20, mental: 80 }, condition: "なし", effect: "自身のヌメリン特効を2％アップ。" },
    { name: "対ヌメリン◎", category: "特殊能力・青", costs: { muscle: 0, agile: 45, tech: 26, intel: 3, mental: 120 }, condition: "なし", effect: "自身のヌメリン特効を3％アップ。" },
    { name: "対キラービー○", category: "特殊能力・青", costs: { muscle: 0, agile: 160, tech: 20, intel: 0, mental: 75 }, condition: "なし", effect: "自身のキラービー特効を2％アップ。" },
    { name: "対キラービー◎", category: "特殊能力・青", costs: { muscle: 0, agile: 240, tech: 30, intel: 0, mental: 113 }, condition: "なし", effect: "自身のキラービー特効を3％アップ。" },
    { name: "対ピクシー○", category: "特殊能力・青", costs: { muscle: 0, agile: 61, tech: 6, intel: 10, mental: 133 }, condition: "なし", effect: "自身のピクシー特効を2％アップ。" },
    { name: "対ピクシー◎", category: "特殊能力・青", costs: { muscle: 0, agile: 92, tech: 9, intel: 20, mental: 199 }, condition: "なし", effect: "自身のピクシー特効を3％アップ。" },
    { name: "対ハーピー○", category: "特殊能力・青", costs: { muscle: 0, agile: 140, tech: 70, intel: 0, mental: 45 }, condition: "なし", effect: "自身のハーピ―特効を2％アップ。" },
    { name: "対ハーピー◎", category: "特殊能力・青", costs: { muscle: 0, agile: 210, tech: 105, intel: 0, mental: 68 }, condition: "なし", effect: "自身のハーピ―特効を3％アップ。" },
    { name: "対スケルトン○", category: "特殊能力・青", costs: { muscle: 110, agile: 100, tech: 0, intel: 0, mental: 135 }, condition: "なし", effect: "自身のスケルトン特効を2％アップ。" },
    { name: "対スケルトン◎", category: "特殊能力・青", costs: { muscle: 165, agile: 150, tech: 0, intel: 0, mental: 203 }, condition: "なし", effect: "自身のスケルトン特効を3％アップ。" },
    { name: "対ラミア○", category: "特殊能力・青", costs: { muscle: 95, agile: 0, tech: 0, intel: 0, mental: 160 }, condition: "なし", effect: "自身のラミア特効を2％アップ。" },
    { name: "対ラミア◎", category: "特殊能力・青", costs: { muscle: 143, agile: 0, tech: 0, intel: 0, mental: 240 }, condition: "なし", effect: "自身のラミア特効を3％アップ。" },
    { name: "対ウンディーネ○", category: "特殊能力・青", costs: { muscle: 0, agile: 55, tech: 0, intel: 120, mental: 80 }, condition: "なし", effect: "自身のウンディーネ特効を2％アップ。" },
    { name: "対ウンディーネ◎", category: "特殊能力・青", costs: { muscle: 0, agile: 83, tech: 0, intel: 180, mental: 120 }, condition: "なし", effect: "自身のウンディーネ特効を3％アップ。" },
    { name: "対フィッシュ○", category: "特殊能力・青", costs: { muscle: 0, agile: 23, tech: 12, intel: 40, mental: 0 }, condition: "なし", effect: "自身のフィッシュ特効を2％アップ。" },
    { name: "対フィッシュ◎", category: "特殊能力・青", costs: { muscle: 0, agile: 34, tech: 7, intel: 36, mental: 0 }, condition: "なし", effect: "自身のフィッシュ特効を3％アップ。" },
    { name: "対妖狐○", category: "特殊能力・青", costs: { muscle: 0, agile: 105, tech: 150, intel: 0, mental: 0 }, condition: "なし", effect: "自身の妖狐特効を2％アップ。" },
    { name: "対妖狐◎", category: "特殊能力・青", costs: { muscle: 0, agile: 158, tech: 225, intel: 0, mental: 0 }, condition: "なし", effect: "自身の妖狐特効を3％アップ。" },
    { name: "対ドラゴンタートル○", category: "特殊能力・青", costs: { muscle: 0, agile: 45, tech: 0, intel: 210, mental: 0 }, condition: "なし", effect: "自身のドラゴンタートル特効を2％アップ。" },
    { name: "対ドラゴンタートル◎", category: "特殊能力・青", costs: { muscle: 0, agile: 68, tech: 0, intel: 315, mental: 0 }, condition: "なし", effect: "自身のドラゴンタートル特効を3％アップ。" },

    // --- サポートスキル・青赤 ---
    { name: "運任せ", category: "特殊能力・青赤", costs: { muscle: 150, agile: 150, tech: 0, intel: 0, mental: 99 }, condition: "なし", effect: "自身の物理攻撃倍率を10％アップ。さらに魔法攻撃倍率を10％アップ。自身の命中率を10％ダウン。" },
    { name: "がむしゃら", category: "特殊能力・青赤", costs: { muscle: 177, agile: 0, tech: 0, intel: 33, mental: 55 }, condition: "なし", effect: "自身の物理攻撃倍率を7％アップ。さらに魔法攻撃耐性を7％アップ。自身の物理攻撃耐性を2％ダウン。さらに魔法攻撃耐性を2％ダウン。" },

    // --- サポートスキル・金 ---
    { name: "怪力Lv.1", category: "特殊能力・金", costs: { muscle: 350, agile: 0, tech: 0, intel: 0, mental: 42 }, condition: "パワーD50", effect: "自身の物理攻撃倍率を12％アップ。さらに魔法攻撃倍率を3％アップ。" },
    { name: "怪力Lv.2", category: "特殊能力・金", costs: { muscle: 406, agile: 0, tech: 0, intel: 0, mental: 48 }, condition: "パワーC60", effect: "自身の物理攻撃倍率を20％アップ。さらに魔法攻撃倍率を5％アップ。" },
    { name: "タフネスLv.1", category: "特殊能力・金", costs: { muscle: 150, agile: 0, tech: 0, intel: 0, mental: 110 }, condition: "生命力D50", effect: "自身のHPを10％アップ。" },
    { name: "タフネスLv.2", category: "特殊能力・金", costs: { muscle: 224, agile: 0, tech: 0, intel: 0, mental: 164 }, condition: "生命力C60", effect: "自身のHPを20％アップ。" },
    { name: "平常心Lv.1", category: "特殊能力・金", costs: { muscle: 466, agile: 81, tech: 240, intel: 148, mental: 0 }, condition: "器用さD50", effect: "自身の通常攻撃倍率を40％アップ。" },
    { name: "烈Lv.1", category: "特殊能力・金", costs: { muscle: 30, agile: 114, tech: 104, intel: 400, mental: 0 }, condition: "器用さD50", effect: "自身の列攻撃倍率を16％アップ。" },
    { name: "烈Lv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 0, tech: 0, intel: 0, mental: 0 }, condition: "器用さC60", effect: "調査中" },
    { name: "剛力Lv.1", category: "特殊能力・金", costs: { muscle: 145, agile: 0, tech: 0, intel: 0, mental: 246 }, condition: "パワーD50", effect: "自身の物理攻撃倍率を12％アップ。さらに魔法攻撃倍率を3％アップ。" },
    { name: "剛力Lv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 0, tech: 0, intel: 0, mental: 0 }, condition: "パワーC50", effect: "調査中" },
    { name: "エースアタッカーLv.1", category: "特殊能力・金", costs: { muscle: 0, agile: 0, tech: 145, intel: 0, mental: 246 }, condition: "パワーD60", effect: "自身の物理攻撃倍率を12％アップ。さらに魔法攻撃倍率を3％アップ。" },
    { name: "エースアタッカーLv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 0, tech: 170, intel: 0, mental: 248 }, condition: "パワーC60", effect: "自身の物理攻撃倍率を20％アップ。さらに魔法攻撃倍率を5％アップ。" },
    { name: "トリックスターLv.1", category: "特殊能力・金", costs: { muscle: 0, agile: 452, tech: 1058, intel: 0, mental: 0 }, condition: "器用さD50", effect: "アクションスキル倍率45%UP" },
    { name: "慈愛の祈りLv.1", category: "特殊能力・金", costs: { muscle: 0, agile: 146, tech: 0, intel: 0, mental: 246 }, condition: "耐久力E40/精神力E40", effect: "自身の物理攻撃耐性を5％アップ。さらに魔法攻撃耐性を5％アップ。" },
    { name: "慈愛の祈りLv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 280, tech: 170, intel: 0, mental: 248 }, condition: "耐久力D40/精神力D50", effect: "自身の物理攻撃耐性を7％アップ。さらに魔法攻撃耐性を7％アップ。" },
    { name: "加護Lv.1", category: "特殊能力・金", costs: { muscle: 0, agile: 208, tech: 92, intel: 92, mental: 0 }, condition: "耐久力E40/精神力E40", effect: "全体攻撃耐性を10％UP" },
    { name: "加護Lv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 240, tech: 106, intel: 106, mental: 0 }, condition: "耐久力D50/精神力D50", effect: "全体攻撃耐性を18％UP" },
    { name: "サイクロプスキラーLv.1", category: "特殊能力・金", costs: { muscle: 588, agile: 142, tech: 0, intel: 50, mental: 0 }, condition: "器用さD50", effect: "サイクロプス特効12％UP" },
    { name: "サイクロプスキラーLv.2", category: "特殊能力・金", costs: { muscle: 0, agile: 0, tech: 0, intel: 0, mental: 0 }, condition: "器用さC60", effect: "調査中" }
];