const SUPPORT_SKILLS = [
  {"name": "物理攻撃○", "category": "サポートスキル・青", "costs": {"muscle": 190, "agile": 15, "tech": 65, "intel": 0, "mental": 0}, "effect": "自身の物理攻撃倍率を3%アップ。", "condition": "なし"},
  {"name": "物理攻撃◎", "category": "サポートスキル・青", "costs": {"muscle": 285, "agile": 22, "tech": 98, "intel": 0, "mental": 0}, "effect": "自身の物理攻撃倍率を5%アップ。", "condition": "なし", "prerequisite": "物理攻撃○"},
  {"name": "魔法攻撃○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 30, "intel": 170, "mental": 70}, "effect": "自身の魔法攻撃倍率を3%アップ。", "condition": "なし"},
  {"name": "魔法攻撃◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 45, "intel": 255, "mental": 105}, "effect": "自身の魔法攻撃倍率を5%アップ。", "condition": "なし", "prerequisite": "魔法攻撃○"},
  {"name": "物理防御○", "category": "サポートスキル・青", "costs": {"muscle": 90, "agile": 150, "tech": 0, "intel": 0, "mental": 35}, "effect": "自身の物理攻撃耐性を2%アップ。", "condition": "なし"},
  {"name": "物理防御◎", "category": "サポートスキル・青", "costs": {"muscle": 135, "agile": 225, "tech": 0, "intel": 0, "mental": 45}, "effect": "自身の物理攻撃耐性を4%アップ。", "condition": "なし", "prerequisite": "物理防御○"},
  {"name": "魔法防御○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 150, "tech": 0, "intel": 70, "mental": 55}, "effect": "自身の魔法攻撃耐性を2%アップ。", "condition": "なし"},
  {"name": "魔法防御◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 225, "tech": 0, "intel": 105, "mental": 75}, "effect": "自身の魔法攻撃耐性を4%アップ。", "condition": "なし", "prerequisite": "魔法防御○"},
  {"name": "体幹", "category": "サポートスキル・青", "costs": {"muscle": 230, "agile": 0, "tech": 0, "intel": 0, "mental": 60}, "effect": "自身の物理攻撃倍率を2%アップ。さらに物理攻撃耐性を1%アップ。", "condition": "なし"},
  {"name": "魔力制御", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 230, "mental": 60}, "effect": "自身の魔法攻撃倍率を2%アップ。さらに魔法攻撃耐性を1%アップ。", "condition": "なし"},
  {"name": "忍耐", "category": "サポートスキル・青", "costs": {"muscle": 170, "agile": 0, "tech": 0, "intel": 0, "mental": 120}, "effect": "自身のHPを3％アップ。", "condition": "なし"},
  {"name": "生存本能", "category": "サポートスキル・青", "costs": {"muscle": 110, "agile": 0, "tech": 0, "intel": 25, "mental": 170}, "effect": "自身のHPを5％アップ。", "condition": "なし"},
  {"name": "闘争本能", "category": "サポートスキル・青", "costs": {"muscle": 80, "agile": 0, "tech": 0, "intel": 0, "mental": 225}, "effect": "自身の物理攻撃倍率を3%アップ。さらに魔法攻撃倍率を3%アップ。", "condition": "なし"},
  {"name": "柔軟な体", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 110, "tech": 140, "intel": 35, "mental": 0}, "effect": "自身の物理攻撃耐性4%アップ。", "condition": "なし"},
  {"name": "頑丈な体", "category": "サポートスキル・青", "costs": {"muscle": 175, "agile": 0, "tech": 0, "intel": 0, "mental": 110}, "effect": "自身のHPを5％アップ。", "condition": "なし"},
  {"name": "無心の構え", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 60, "tech": 30, "intel": 0, "mental": 195}, "effect": "自身の魔法攻撃耐性4%アップ。", "condition": "なし"},
  {"name": "護身の構え", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 110, "tech": 105, "intel": 0, "mental": 70}, "effect": "自身のHPを5％アップ。", "condition": "なし"},
  {"name": "狙い撃ち", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 195, "intel": 0, "mental": 95}, "effect": "自身の命中率を2％アップ。", "condition": "なし"},
  {"name": "火攻撃", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 180, "intel": 40, "mental": 60}, "effect": "自身の火属性倍率3%アップ。", "condition": "火属性"},
  {"name": "風攻撃", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 180, "intel": 40, "mental": 60}, "effect": "自身の風属性倍率3%アップ。", "condition": "風属性"},
  {"name": "水攻撃", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 180, "intel": 40, "mental": 60}, "effect": "自身の水属性倍率3%アップ。", "condition": "水属性"},
  {"name": "火耐性", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 120, "tech": 60, "intel": 0, "mental": 100}, "effect": "自身の火属性耐性を2％アップ。", "condition": "なし"},
  {"name": "風耐性", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 120, "tech": 60, "intel": 0, "mental": 100}, "effect": "自身の風属性耐性を2％アップ。", "condition": "なし"},
  {"name": "水耐性", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 120, "tech": 60, "intel": 0, "mental": 100}, "effect": "自身の水属性耐性を2％アップ。", "condition": "なし"},
  {"name": "無耐性", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 120, "tech": 60, "intel": 0, "mental": 100}, "effect": "自身の無属性耐性を2％アップ。", "condition": "なし"},
  {"name": "通常攻撃○", "category": "サポートスキル・青", "costs": {"muscle": 95, "agile": 85, "tech": 90, "intel": 0, "mental": 0}, "effect": "自身の通常攻撃倍率を12%アップ。", "condition": "なし"},
  {"name": "通常攻撃◎", "category": "サポートスキル・青", "costs": {"muscle": 143, "agile": 112, "tech": 135, "intel": 0, "mental": 0}, "effect": "自身の通常攻撃倍率を20%アップ。", "condition": "なし", "prerequisite": "通常攻撃○"},
  {"name": "アクションスキル○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 90, "tech": 170, "intel": 0, "mental": 0}, "effect": "自身のアクションスキル倍率を12%アップ。", "condition": "なし"},
  {"name": "アクションスキル◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 135, "tech": 255, "intel": 0, "mental": 0}, "effect": "自身のアクションスキル倍率を20%アップ。", "condition": "なし", "prerequisite": "アクションスキル○"},
  {"name": "単体攻撃○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 90, "intel": 0, "mental": 300}, "effect": "自身の単体攻撃倍率を3%アップ。", "condition": "なし"},
  {"name": "単体攻撃◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 60, "intel": 0, "mental": 200}, "effect": "自身の単体攻撃倍率を3%アップ。", "condition": "なし", "prerequisite": "単体攻撃○"},
  {"name": "列攻撃○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 160, "tech": 50, "intel": 50, "mental": 0}, "effect": "自身の列攻撃倍率を3%アップ。", "condition": "なし"},
  {"name": "列攻撃◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 240, "tech": 75, "intel": 75, "mental": 0}, "effect": "自身の列攻撃倍率を3%アップ。", "condition": "なし", "prerequisite": "列攻撃○"},
  {"name": "追撃○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 130, "tech": 130, "intel": 0, "mental": 0}, "effect": "自身の追撃倍率を3%アップ。", "condition": "なし"},
  {"name": "追撃◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 195, "tech": 195, "intel": 0, "mental": 0}, "effect": "自身の追撃倍率を5%アップ。", "condition": "なし", "prerequisite": "追撃○"},
  {"name": "けがしにくさ○", "category": "サポートスキル・青", "costs": {"muscle": 190, "agile": 0, "tech": 0, "intel": 0, "mental": 80}, "effect": "自身の物理攻撃耐性を1％アップ。さらに魔法攻撃耐性を1％アップ。", "condition": "なし"},
  {"name": "けがしにくさ◎", "category": "サポートスキル・青", "costs": {"muscle": 285, "agile": 0, "tech": 0, "intel": 0, "mental": 120}, "effect": "自身の物理攻撃耐性を2％アップ。さらに魔法攻撃耐性を2％アップ。", "condition": "なし", "prerequisite": "けがしにくさ○"},
  {"name": "防御体制", "category": "サポートスキル・青", "costs": {"muscle": 155, "agile": 135, "tech": 0, "intel": 0, "mental": 0}, "effect": "自身の単体攻撃耐性を2％アップ。", "condition": "なし"},
  {"name": "備え", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 60, "intel": 90, "mental": 140}, "effect": "自身の列攻撃耐性を2％アップ。", "condition": "なし"},
  {"name": "広い視野", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 170, "tech": 0, "intel": 60, "mental": 60}, "effect": "自身の全体攻撃耐性を2％アップ。", "condition": "なし"},
  {"name": "見切り", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 65, "tech": 95, "intel": 130, "mental": 0}, "effect": "自身のアクションスキル耐性4%アップ。", "condition": "なし"},
  {"name": "危機察知", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 120, "tech": 50, "intel": 115, "mental": 0}, "effect": "自身の必殺技耐性を4％アップ。", "condition": "なし"},
  {"name": "力学の理解", "category": "サポートスキル・青", "costs": {"muscle": 80, "agile": 0, "tech": 0, "intel": 230, "mental": 0}, "effect": "自身の物理攻撃耐性を4％アップ。", "condition": "なし"},
  {"name": "魔法の理解", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 310, "mental": 0}, "effect": "自身の魔法攻撃耐性を4％アップ。", "condition": "なし"},
  {"name": "免疫強化", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 70, "tech": 0, "intel": 86, "mental": 104}, "effect": "自身のダメージ状態異常耐性を2%アップ。", "condition": "なし"},
  {"name": "意志", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 14, "mental": 246}, "effect": "自身の弱体化状態異常耐性を2%アップ。", "condition": "なし"},
  {"name": "ガッツ", "category": "サポートスキル・青", "costs": {"muscle": 14, "agile": 0, "tech": 0, "intel": 0, "mental": 246}, "effect": "自身の行動不能状態異常耐性を2%アップ。", "condition": "なし"},
  {"name": "対剣士○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 90, "tech": 0, "intel": 170, "mental": 10}, "effect": "自身の剣士特効を2％アップ。", "condition": "なし"},
  {"name": "対剣士◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 135, "tech": 0, "intel": 255, "mental": 15}, "effect": "自身の剣士特効を3％アップ。", "condition": "なし", "prerequisite": "対剣士○"},
  {"name": "対魔闘士○", "category": "サポートスキル・青", "costs": {"muscle": 25, "agile": 40, "tech": 0, "intel": 0, "mental": 205}, "effect": "自身の魔闘士特効を2％アップ。", "condition": "なし"},
  {"name": "対魔闘士◎", "category": "サポートスキル・青", "costs": {"muscle": 37, "agile": 60, "tech": 0, "intel": 0, "mental": 308}, "effect": "自身の魔闘士特効を3％アップ。", "condition": "なし", "prerequisite": "対魔闘士○"},
  {"name": "対弓使い○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 205, "tech": 0, "intel": 0, "mental": 65}, "effect": "自身の弓使い特効を2％アップ。", "condition": "なし"},
  {"name": "対弓使い◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 308, "tech": 0, "intel": 0, "mental": 97}, "effect": "自身の弓使い特効を3％アップ。", "condition": "なし", "prerequisite": "対弓使い○"},
  {"name": "対魔法使い○", "category": "サポートスキル・青", "costs": {"muscle": 170, "agile": 30, "tech": 0, "intel": 0, "mental": 70}, "effect": "自身の魔法使い特効を2％アップ。", "condition": "なし"},
  {"name": "対魔法使い◎", "category": "サポートスキル・青", "costs": {"muscle": 255, "agile": 45, "tech": 0, "intel": 0, "mental": 105}, "effect": "自身の魔法使い特効を3％アップ。", "condition": "なし", "prerequisite": "対魔法使い○"},
  {"name": "対ゴブリン○", "category": "サポートスキル・青", "costs": {"muscle": 95, "agile": 0, "tech": 80, "intel": 80, "mental": 0}, "effect": "自身のゴブリン特効を2％アップ。", "condition": "なし"},
  {"name": "対ゴブリン◎", "category": "サポートスキル・青", "costs": {"muscle": 143, "agile": 0, "tech": 120, "intel": 120, "mental": 0}, "effect": "自身のゴブリン特効を3％アップ。", "condition": "なし", "prerequisite": "対ゴブリン○"},
  {"name": "対オーク○", "category": "サポートスキル・青", "costs": {"muscle": 220, "agile": 35, "tech": 0, "intel": 0, "mental": 0}, "effect": "自身のオーク特効を2％アップ。", "condition": "なし"},
  {"name": "対オーク◎", "category": "サポートスキル・青", "costs": {"muscle": 330, "agile": 53, "tech": 0, "intel": 0, "mental": 0}, "effect": "自身のオーク特効を3％アップ。", "condition": "なし", "prerequisite": "対オーク○"},
  {"name": "対サイクロプス○", "category": "サポートスキル・青", "costs": {"muscle": 80, "agile": 125, "tech": 0, "intel": 50, "mental": 0}, "effect": "自身のサイクロプス特効を2％アップ。", "condition": "なし"},
  {"name": "対サイクロプス◎", "category": "サポートスキル・青", "costs": {"muscle": 120, "agile": 188, "tech": 0, "intel": 75, "mental": 0}, "effect": "自身のサイクロプス特効を3％アップ。", "condition": "なし", "prerequisite": "対サイクロプス○"},
  {"name": "対ヌメリン○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 30, "tech": 17, "intel": 208, "mental": 0}, "effect": "自身のヌメリン特効を2％アップ。", "condition": "なし"},
  {"name": "対ヌメリン◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 45, "tech": 26, "intel": 312, "mental": 0}, "effect": "自身のヌメリン特効を3％アップ。", "condition": "なし", "prerequisite": "対ヌメリン○"},
  {"name": "対キラービー○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 160, "tech": 20, "intel": 0, "mental": 75}, "effect": "自身のキラービー特効を2％アップ。", "condition": "なし"},
  {"name": "対キラービー◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 240, "tech": 30, "intel": 0, "mental": 113}, "effect": "自身のキラービー特効を3％アップ。", "condition": "なし", "prerequisite": "対キラービー○"},
  {"name": "対ピクシー○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 61, "tech": 61, "intel": 0, "mental": 133}, "effect": "自身のピクシー特効を2％アップ。", "condition": "なし"},
  {"name": "対ピクシー◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 92, "tech": 92, "intel": 0, "mental": 199}, "effect": "自身のピクシー特効を3％アップ。", "condition": "なし", "prerequisite": "対ピクシー○"},
  {"name": "対ハーピー○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 140, "tech": 70, "intel": 0, "mental": 45}, "effect": "自身のハーピ―特効を2％アップ。", "condition": "なし"},
  {"name": "対ハーピー◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 210, "tech": 105, "intel": 0, "mental": 68}, "effect": "自身のハーピ―特効を3％アップ。", "condition": "なし", "prerequisite": "対ハーピー○"},
  {"name": "対スケルトン○", "category": "サポートスキル・青", "costs": {"muscle": 110, "agile": 10, "tech": 0, "intel": 0, "mental": 135}, "effect": "自身のスケルトン特効を2％アップ。", "condition": "なし"},
  {"name": "対スケルトン◎", "category": "サポートスキル・青", "costs": {"muscle": 165, "agile": 15, "tech": 0, "intel": 0, "mental": 203}, "effect": "自身のスケルトン特効を3％アップ。", "condition": "なし", "prerequisite": "対スケルトン○"},
  {"name": "対ラミア○", "category": "サポートスキル・青", "costs": {"muscle": 95, "agile": 0, "tech": 0, "intel": 0, "mental": 160}, "effect": "自身のラミア特効を2％アップ。", "condition": "なし"},
  {"name": "対ラミア◎", "category": "サポートスキル・青", "costs": {"muscle": 143, "agile": 0, "tech": 0, "intel": 0, "mental": 240}, "effect": "自身のラミア特効を3％アップ。", "condition": "なし", "prerequisite": "対ラミア○"},
  {"name": "対ウンディーネ○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 55, "tech": 0, "intel": 120, "mental": 80}, "effect": "自身のウンディーネ特効を2％アップ。", "condition": "なし"},
  {"name": "対ウンディーネ◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 83, "tech": 0, "intel": 180, "mental": 120}, "effect": "自身のウンディーネ特効を3％アップ。", "condition": "なし", "prerequisite": "対ウンディーネ○"},
  {"name": "対フィッシュ○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 231, "tech": 24, "intel": 0, "mental": 0}, "effect": "自身のフィッシュ特効を2％アップ。", "condition": "なし"},
  {"name": "対フィッシュ◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 347, "tech": 36, "intel": 0, "mental": 0}, "effect": "自身のフィッシュ特効を3％アップ。", "condition": "なし", "prerequisite": "対フィッシュ○"},
  {"name": "対妖狐○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 105, "tech": 150, "intel": 0, "mental": 0}, "effect": "自身の妖狐特効を2％アップ。", "condition": "なし"},
  {"name": "対妖狐◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 158, "tech": 225, "intel": 0, "mental": 0}, "effect": "自身の妖狐特効を3％アップ。", "condition": "なし", "prerequisite": "対妖狐○"},
  {"name": "対ドラゴンタートル○", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 45, "tech": 0, "intel": 210, "mental": 0}, "effect": "自身のドラゴンタートル特効を2％アップ。", "condition": "なし"},
  {"name": "対ドラゴンタートル◎", "category": "サポートスキル・青", "costs": {"muscle": 0, "agile": 68, "tech": 0, "intel": 315, "mental": 0}, "effect": "自身のドラゴンタートル特効を3％アップ。", "condition": "なし", "prerequisite": "対ドラゴンタートル○"},
  {"name": "運任せ", "category": "サポートスキル・青赤", "costs": {"muscle": 150, "agile": 0, "tech": 0, "intel": 0, "mental": 99}, "effect": "自身の物理攻撃倍率を10％アップ。命中率10％ダウン。", "condition": "なし"},
  {"name": "がむしゃら", "category": "サポートスキル・青赤", "costs": {"muscle": 177, "agile": 0, "tech": 0, "intel": 33, "mental": 55}, "effect": "自身の物理攻撃倍率を7％アップ。魔法攻撃耐性を7％アップ。", "condition": "なし"},
  {"name": "平常心Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 32, "tech": 80, "intel": 0, "mental": 148}, "effect": "自身の通常攻撃倍率を40％アップ。", "condition": "器用さD50", "prerequisite": "通常攻撃◎"},
  {"name": "平常心Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 48, "tech": 120, "intel": 0, "mental": 222}, "effect": "自身の通常攻撃倍率を70％アップ。", "condition": "器用さC60", "prerequisite": "平常心Lv.1"},
  {"name": "烈Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 114, "tech": 104, "intel": 40, "mental": 0}, "effect": "自身の列攻撃倍率を16％アップ。", "condition": "器用さD50", "prerequisite": "列攻撃◎"},
  {"name": "烈Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 0, "mental": 0}, "effect": "自身の列攻撃倍率を28％アップ。", "condition": "器用さC60", "prerequisite": "烈Lv.1"},
  {"name": "トリックスターLv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 452, "tech": 105, "intel": 80, "mental": 0}, "effect": "アクションスキル倍率45%UP", "condition": "器用さD50"},
  {"name": "タフネスLv.1", "category": "サポートスキル・金", "costs": {"muscle": 150, "agile": 0, "tech": 0, "intel": 0, "mental": 110}, "effect": "自身のHPを10％アップ。", "condition": "生命力D50", "prerequisite": "忍耐"},
  {"name": "タフネスLv.2", "category": "サポートスキル・金", "costs": {"muscle": 224, "agile": 0, "tech": 0, "intel": 0, "mental": 164}, "effect": "自身のHPを20％アップ。", "condition": "生命力C60", "prerequisite": "タフネスLv.1"},
  {"name": "加護Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 208, "tech": 0, "intel": 92, "mental": 92}, "effect": "全体攻撃耐性を10％UP", "condition": "耐久力E40/精神力E40"},
  {"name": "加護Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 240, "tech": 0, "intel": 106, "mental": 106}, "effect": "全体攻撃耐性を18％UP", "condition": "耐久力D50/精神力D50", "prerequisite": "加護Lv.1"},
  {"name": "慈愛の祈りLv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 146, "tech": 0, "intel": 0, "mental": 246}, "effect": "自身の物理攻撃耐性を5％アップ。さらに魔法攻撃耐性を5％アップ。", "condition": "耐久力E40/精神力E40"},
  {"name": "慈愛の祈りLv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 170, "tech": 0, "intel": 0, "mental": 248}, "effect": "自身の物理攻撃耐性を7％アップ。さらに魔法攻撃耐性を7％アップ。", "condition": "耐久力D40/精神力D50", "prerequisite": "慈愛の祈りLv.1"},
  {"name": "怪力Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 350, "agile": 0, "tech": 0, "intel": 0, "mental": 42}, "effect": "自身の物理攻撃倍率を12％アップ。さらに魔法攻撃倍率を3％アップ。", "condition": "パワーD50"},
  {"name": "怪力Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 406, "agile": 0, "tech": 0, "intel": 0, "mental": 48}, "effect": "自身の物理攻撃倍率を20％アップ。さらに魔法攻撃倍率を5％アップ。", "condition": "パワーC60", "prerequisite": "怪力Lv.1"},
  {"name": "剛力Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 146, "agile": 0, "tech": 0, "intel": 0, "mental": 246}, "effect": "自身の物理攻撃倍率を12％アップ。", "condition": "パワーD50"},
  {"name": "剛力Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 170, "agile": 0, "tech": 0, "intel": 0, "mental": 284}, "effect": "自身の物理攻撃倍率を20％アップ。", "condition": "パワーC50", "prerequisite": "剛力Lv.1"},
  {"name": "エースアタッカーLv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 146, "intel": 0, "mental": 246}, "effect": "自身の物理攻撃倍率を12％アップ。", "condition": "パワーD60"},
  {"name": "エースアタッカーLv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 170, "intel": 0, "mental": 284}, "effect": "自身の物理攻撃倍率を20％アップ。", "condition": "パワーC60", "prerequisite": "エースアタッカーLv.1"},
  {"name": "魔力増強Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 328, "mental": 64}, "effect": "自身の魔法攻撃倍率を12％アップ。さらに物理攻撃倍率を3％アップ。", "condition": "魔力D50"},
  {"name": "魔力増強Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 378, "mental": 74}, "effect": "自身の魔法攻撃倍率を20％アップ。さらに物理攻撃倍率を5％アップ。", "condition": "魔力C60", "prerequisite": "魔力増強Lv.1"},
  {"name": "魔力探求Lv.1", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 146, "mental": 243}, "effect": "自身の魔法攻撃倍率を12％アップ。さらに物理攻撃倍率を3％アップ。", "condition": "魔力D50"},
  {"name": "魔力探求Lv.2", "category": "サポートスキル・金", "costs": {"muscle": 0, "agile": 0, "tech": 0, "intel": 170, "mental": 282}, "effect": "自身の魔法攻撃倍率を20％アップ。さらに物理攻撃倍率を5％アップ。", "condition": "魔力C60", "prerequisite": "魔力探求Lv.1"},
  {"name": "サイクロプスキラーLv.1", "category": "サポートスキル・金", "costs": {"muscle": 88, "agile": 142, "tech": 0, "intel": 50, "mental": 0}, "effect": "サイクロプス特効12％UP", "condition": "器用さD50", "prerequisite": "対サイクロプス◎"}
];